baseURL = "/"
languageCode = "es-cr"
title = "Pura Vida Lounge"

theme = "hugo-strata-theme"
disqusShortname = "puravidelounge"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Pura Vida Lounge"
	description = "Lo mejor en comida de Costa Rica y centroamerica"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "logo.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Pura Vida Lounge"
		# The icons will be shown if you enter your username
		twitter = ""
		facebook = "puravidalounge"
		googleplus = ""


		copyright = [
			"&copy; Pura Vida Lounge",
			"Diseño: Gabriel Brown",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Lo mejor en comida de Costa Rica y CentroAmerica"
		content = ""


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/IMG_0409.jpeg"
			thumb = "thumbs/IMG_0409.jpeg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/IMG_0426.jpeg"
			thumb = "thumbs/IMG_0426.jpeg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/IMG_0654.jpeg"
			thumb = "thumbs/IMG_0654.jpeg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/IMG_0577.jpeg"
			thumb = "thumbs/IMG_0577.jpeg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/IMG_0579.jpeg"
			thumb = "thumbs/IMG_0579.jpeg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/IMG_0589.jpeg"
			thumb = "thumbs/IMG_0589.jpeg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = true
		title = "Blog Posts recientes"

	[params.contact]
		hide  = false
		title = "Contactenos"
		content = "Dejenos su mensaje."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "40.2090039,-74.7454793"
		address = [
			"228 Cummings Ave",
			"Trenton, New Jersey 08611",
			"United States"
		]
		phone = "609-396-7472"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Nombre"
			email = "Correo"
			message = "Mensaje"
			submit = "Dejar Mensaje"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0
